#!/usr/bin/env bash

# Sandfly Security LTD www.sandflysecurity.com
# Copyright (c) Sandfly Security LTD, All Rights Reserved.

# This script will generate Docker Compose resource definitions to install the
# Sandfly server and node. Secrets will be randomly generated and initial
# configuration values seeded.

# If any required command line flags are not provided, the setuphelper tool
# will interactively prompt for values.
#
# To run non-interactively, run script with all of the following parameters:
#
# -admin-password <password>
#    **OR**
# -skipadminpw
#    If a password is provided, the hashed password will be used to set the
#    Sandfly admin account on first server startup. The provided password
#    may be plaintext, or it may be a pre-hashed password as generated by the
#    "setuphelper hashpw" tool.
#
#    If instead of providing a password the -skipadminpw flag is used,
#    the generated Docker compose configuration will NOT set an initial admin
#    password, and the first user to access the Sandfly web interface after
#    startup will be able to set the admin password via the web browser.
#
# -hostname <hostname>
#    hostname/FQDN/IP address users will use to access server UI
#
# -tls-mode { self_signed | acme | user_managed | none }
#    Initial server HTTPS (TLS) certificate mode:
#      * self_signed:  at first startup, Sandfly server will generate a
#                      self-signed certificate.
#      * acme:         Sandfly will request a certificate from an ACME
#                      (e.g. Let's Encrypt by default) service, using the
#                      hostname provided by the -hostname parameter. The
#                      server must be accessible to the provider on port 443 at
#                      that hostname at startup.
#      * user_managed: certificate and key in setup_data/server_ssl_cert
#                      will be mounted in the server container;
#                      you will be responsible for managing the certificate.
#      * none:         Sandfly server should only run plain HTTP server and
#                      HTTPS will be provided by a proxy container or similar
#                      arrangement.
#
# If tls-mode is "acme", then an email address is required:
#
# -acme-email <email address>
#
# And if tls-mode is "acme", you may optionally switch to a provider other
# than the default production Let's Encrypt service:
#
# -acme-directory <ACME directory service URL>
#    Defaults to "https://acme-v02.api.letsencrypt.org/directory"
#

###############################################################################
###############################################################################
###############################################################################

# Make sure we run from the correct directory so relative paths work
cd "$( dirname "${BASH_SOURCE[0]}" )"
SETUP_DATA_DIR=./setup_data
VERSION=${SANDFLY_SETUP_VERSION:-$(cat ../VERSION)}
PG_VERSION_18=$(grep -oP 'VERSION=\K(18\.[0-9]+)' ../start_scripts/start_postgres.sh | head -n1)

cat << "__EOF__"


 _____                 _  __ _         _____                      _ _
/  ___|               | |/ _| |       /  ___|                    (_) |
\ `--.  __ _ _ __   __| | |_| |_   _  \ `--.  ___  ___ _   _ _ __ _| |_ _   _
 `--. \/ _` | '_ \ / _` |  _| | | | |  `--. \/ _ \/ __| | | | '__| | __| | | |
/\__/ / (_| | | | | (_| | | | | |_| | /\__/ /  __/ (__| |_| | |  | | |_| |_| |
\____/ \__,_|_| |_|\__,_|_| |_|\__, | \____/ \___|\___|\__,_|_|  |_|\__|\__, |
                     .          __/ |              .                     __/ |
                    //         |___/               \\                   |___/
                   //                               \\
                  //                                 \\
                 //                _._                \\
              .---.              .//|\\.              .---.
    ________ / .-. \_________..-~ _.-._ ~-..________ / .-. \_________ -sr
             \ ~-~ /   /H-     `-=.___.=-'     -H\   \ ~-~ /
               ~~~    / H          [H]          H \    ~~~
                     / _H_         _H_         _H_ \
                       UUU         UUU         UUU
__EOF__

for x in config.server.env config.node.env config.postgres.env docker-compose.yaml; do
    if [ -f "$SETUP_DATA_DIR/$x" ]; then
        echo ""
        echo "********************************** ERROR **********************************"
        echo " The file $x already exists in the setup_data directory."
        echo " Remove existing files if you wish to generate new ones."
        echo "********************************** ERROR **********************************"
        echo ""
        exit 1
    fi
done

cat << EOF

Installing Sandfly server version $VERSION.

Copyright (c) Sandfly Security Ltd.

Welcome to the Sandfly $VERSION server setup. This script will generate
Docker compose files for deploying Sandfly.

EOF

# Load images if offline bundle is present and not already loaded
./setup_scripts/load_images.sh
if [ "$?" -ne 0 ]; then
  echo "Error loading container images."
  exit 1
fi

./setup_scripts/setuphelper compose -postgres-version "$PG_VERSION_18" -output-dir "$SETUP_DATA_DIR" "$@"

if [ $? -eq 0 ]; then
    echo ""
    echo "Docker compose and environment files generated in"
    echo "  $(readlink -f "$SETUP_DATA_DIR")"
    echo ""
    echo "To start Sandfly, navigate to the directory ${SETUP_DATA_DIR}"
    echo ""
    echo "To run both the Sandfly server and nodes on this system, use the default"
    echo "'docker-compose.yaml' file:"
    echo "  cd ${SETUP_DATA_DIR}"
    echo "  docker compose up -d"
    echo ""
    echo "To run just the Sandfly server on this system, use the server only"
    echo "'docker-compose-server_only.yaml' file:"
    echo "  cd ${SETUP_DATA_DIR}"
    echo "  docker compose -f docker-compose-server_only.yaml up -d"
    echo ""
    echo "To run the Sandfly nodes on a different system, copy the node only"
    echo "'docker-compose-node_only.yaml' file and the 'config.node.env' file"
    echo "to the target system and use the command:"
    echo "  docker compose -f docker-compose-node_only.yaml up -d"
    echo ""
    echo "For more information see the documentation at the following URL:"
    echo "  https://docs.sandflysecurity.com/"
    echo ""
fi
