#!/usr/bin/env bash

# Sandfly Security LTD www.sandflysecurity.com
# Copyright (c) Sandfly Security LTD, All Rights Reserved.

# This script will generate Kubernetes resource definitions to install the
# Sandfly server and nodes. Secrets will be randomly generated and initial
# configuration values seeded.

# If any required command line flags are not provided, the setuphelper tool
# will interactively prompt for values.
#
# To run non-interactively, run script with all of the following parameters:
#
# -admin-password <password>
#    **OR**
# -skipadminpw
#    If a password is provided, the hashed password will be used to set the
#    Sandfly admin account on first server startup. The provided password
#    may be plaintext, or it may be a pre-hashed password as generated by the
#    "setuphelper hashpw" tool.
#
#    If instead of providing a password the -skipadminpw flag is used,
#    the generate Kubernetes configuration will NOT set an initial admin
#    password, and the first user to access the Sandfly web interface after
#    startup will be able to set the admin password via the web browser.
#
# -hostname <hostname>
#    hostname/FQDN/IP address users will use to access server UI
#
# -tls-mode { self_signed | acme | user_managed | none }
#    Initial server HTTPS (TLS) certificate mode:
#      * self_signed:  at first startup, Sandfly server will generate a
#                      self-signed certificate.
#      * acme:         Sandfly will request a certificate from an ACME
#                      (e.g. Let's Encrypt by default) service, using the
#                      hostname provided by the -hostname parameter. The
#                      server must be accessible to the provider on port 443 at
#                      that hostname at startup.
#      * user_managed: certificate and key will be mounted in the server pod;
#                      you will be responsible for managing the certificate.
#                      (Server will fall back to self_signed if user
#                      certificates can't be loaded.)
#      * none:         Sandfly server should only run plain HTTP server and
#                      HTTPS will be provided by an ingress/proxy/etc. pod.
#
# -pg-cpus <number>
#    Number of CPU cores to calculate Postgres tuning parameters for.
#
# -pg-ram-gb <number>
#    Number of gigabytes of RAM to calculate Postgres tuning parameters for.
#
# -storage-size-gb <number>
#    Size, in gigabytes, for the persistent volume for the Postgres database.
#
# If tls-mode is "acme", then an email address is required:
#
# -acme-email <email address>
#
# And if tls-mode is "acme", you may optionally switch to a provider other
# than the default production Let's Encrypt service:
#
# -acme-directory <ACME directory service URL>
#    Defaults to "https://acme-v02.api.letsencrypt.org/directory"
#
# Finally, there is an optional parameter to set the Kubernetes namespace
# for the generated resources:
#
# -namespace <string>
#    Defaults to "sandfly"
#

###############################################################################
###############################################################################
###############################################################################

# Make sure we run from the correct directory so relative paths work
cd "$( dirname "${BASH_SOURCE[0]}" )"
SETUP_DATA_DIR=./setup_data
VERSION=${SANDFLY_SETUP_VERSION:-$(cat ../VERSION)}
PG_VERSION_18=$(grep -oP 'VERSION=\K(18\.[0-9]+)' ../start_scripts/start_postgres.sh | head -n1)

cat << "__EOF__"


 _____                 _  __ _         _____                      _ _
/  ___|               | |/ _| |       /  ___|                    (_) |
\ `--.  __ _ _ __   __| | |_| |_   _  \ `--.  ___  ___ _   _ _ __ _| |_ _   _
 `--. \/ _` | '_ \ / _` |  _| | | | |  `--. \/ _ \/ __| | | | '__| | __| | | |
/\__/ / (_| | | | | (_| | | | | |_| | /\__/ /  __/ (__| |_| | |  | | |_| |_| |
\____/ \__,_|_| |_|\__,_|_| |_|\__, | \____/ \___|\___|\__,_|_|  |_|\__|\__, |
                     .          __/ |              .                     __/ |
                    //         |___/               \\                   |___/
                   //                               \\
                  //                                 \\
                 //                _._                \\
              .---.              .//|\\.              .---.
    ________ / .-. \_________..-~ _.-._ ~-..________ / .-. \_________ -sr
             \ ~-~ /   /H-     `-=.___.=-'     -H\   \ ~-~ /
               ~~~    / H          [H]          H \    ~~~
                     / _H_         _H_         _H_ \
                       UUU         UUU         UUU
__EOF__

for x in sandfly-secrets.yaml sandfly-config.yaml sandfly-deploy.yaml sandfly-loadbalancer.yaml; do
    if [ -f "$SETUP_DATA_DIR/$x" ]; then
        echo ""
        echo "********************************** ERROR **********************************"
        echo " The file $x already exists in the setup_data directory."
        echo " Remove existing Kubernetes yaml files if you wish to generate new ones."
        echo "********************************** ERROR **********************************"
        echo ""
        exit 1
    fi
done

cat << EOF

Installing Sandfly server version $VERSION.

Copyright (c) Sandfly Security Ltd.

Welcome to the Sandfly $VERSION server setup. This script will generate
Kubernetes manifest files for deploying Sandfly.

EOF

./setup_scripts/setuphelper k8s -postgres-version "$PG_VERSION_18" -output-dir "$SETUP_DATA_DIR" "$@"

if [ $? -eq 0 ]; then
    echo ""
    echo "K8s yaml files generated in"
    echo "  $(readlink -f "$SETUP_DATA_DIR")"
    echo ""
fi
